version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: pratclot.com.backend
    ports:
      - "1337:1337"
    env_file:
      - backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - "build"

  frontend:
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
      network: host
    image: pratclot.com.frontend
    container_name: pratclot.com.frontend
    ports:
      - "8000:80"
    profiles:
      - "build"

  gatsby:
    image: pratclot.com.frontend:latest
    container_name: pratclot.com.frontend
    restart: unless-stopped
    ports:
      - "30080:80"
    profiles:
      - "deploy"
